/**
 * Thin typed client over the FastAPI backend.
 *
 * Every request and response type is derived from `schema.d.ts`, which is
 * generated by `npm run api:types`. Nothing here hand-writes a shape: if the
 * backend renames a field, this file keeps compiling and the *call sites*
 * break, which is the entire point of the setup.
 *
 * Regenerate after any Pydantic model change.
 */

import type { components, paths } from "./schema";

/** Shorthand for the generated response/request models. */
export type Schemas = components["schemas"];

// ---------------------------------------------------------------------------
// Type plumbing
// ---------------------------------------------------------------------------

/**
 * Methods a path actually implements. openapi-typescript emits unsupported
 * verbs as `put?: never`, so presence alone is not enough to test on — an
 * implemented operation is distinguished by having `responses`.
 */
type ImplementedMethods<P extends keyof paths> = {
  [M in keyof paths[P]]-?: paths[P][M] extends { responses: unknown } ? M : never;
}[keyof paths[P]];

/** Union of paths supporting a given method — keeps typos out of call sites. */
export type PathsWith<M extends string> = {
  [P in keyof paths]: M extends ImplementedMethods<P> ? P : never;
}[keyof paths];

type Operation<P extends keyof paths, M extends string> = M extends keyof paths[P]
  ? paths[P][M]
  : never;

type OkBody<O> = O extends { responses: { 200: { content: { "application/json": infer T } } } }
  ? T
  : never;

type QueryParams<O> = O extends { parameters: { query?: infer Q } } ? Q : never;
type PathParams<O> = O extends { parameters: { path?: infer T } } ? T : never;
type JsonBody<O> = O extends { requestBody: { content: { "application/json": infer B } } }
  ? B
  : never;

/**
 * Require a key only when the operation actually has that parameter.
 *
 * Both empty shapes have to be treated as absent: an operation with no request
 * body infers `never`, while one with no path params infers `undefined`,
 * because openapi-typescript writes those as `path?: never`. Checking only for
 * `never` makes every parameterless call carry a pointless `path: undefined`.
 */
type Requires<K extends string, T> = [T] extends [never]
  ? { [k in K]?: never }
  : undefined extends T
    ? { [k in K]?: Exclude<T, undefined> }
    : { [k in K]: T };

type RequestOptions<P extends keyof paths, M extends string> = Requires<
  "path",
  PathParams<Operation<P, M>>
> &
  Requires<"body", JsonBody<Operation<P, M>>> & {
    query?: QueryParams<Operation<P, M>>;
    signal?: AbortSignal;
  };

/** The response type for a given path + method, for use in query generics. */
export type ResponseOf<P extends keyof paths, M extends string> = OkBody<Operation<P, M>>;

/** Keys of `T` that cannot be omitted. */
type RequiredKeys<T> = {
  [K in keyof T]-?: object extends Pick<T, K> ? never : K;
}[keyof T];

/**
 * Make the options argument itself required when the operation has a required
 * parameter. Without this, `api.get("/opportunities/{opportunity_id}")` — with
 * the path param simply left off — type-checks and fails at runtime instead.
 */
type Args<P extends keyof paths, M extends string> = [
  RequiredKeys<RequestOptions<P, M>>,
] extends [never]
  ? [options?: RequestOptions<P, M>]
  : [options: RequestOptions<P, M>];

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * Read from the environment, never hardcoded at a call site. `NEXT_PUBLIC_` is
 * required because client components read this after bundling, where only
 * inlined public vars exist.
 */
export const API_BASE_URL = (
  process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"
).replace(/\/$/, "");

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/** A non-2xx response. Carries FastAPI's `detail` through for the UI to read. */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly url: string,
    readonly detail: unknown,
  ) {
    super(`${status} ${url}: ${describeDetail(detail) ?? "request failed"}`);
    this.name = "ApiError";
  }

  /** 422 from FastAPI's request validation, as opposed to a raised HTTPException. */
  get isValidationError() {
    return this.status === 422;
  }
}

/**
 * FastAPI puts a plain string in `detail` for a raised HTTPException, and a
 * list of per-field objects for request-validation failures. Flatten both to
 * something showable rather than letting `[object Object]` reach the UI.
 */
function describeDetail(detail: unknown): string | undefined {
  if (typeof detail === "string") return detail;
  if (Array.isArray(detail)) {
    const parts = detail
      .map((item) =>
        item && typeof item === "object" && "msg" in item
          ? String((item as { msg: unknown }).msg)
          : undefined,
      )
      .filter(Boolean);
    if (parts.length) return parts.join("; ");
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// URL building
// ---------------------------------------------------------------------------

function buildUrl(
  template: string,
  pathParams?: Record<string, unknown>,
  query?: Record<string, unknown>,
): string {
  let path = template;

  if (pathParams) {
    for (const [key, value] of Object.entries(pathParams)) {
      path = path.replace(`{${key}}`, encodeURIComponent(String(value)));
    }
  }

  const unresolved = path.match(/\{([^}]+)\}/);
  if (unresolved) {
    throw new Error(`Missing path parameter "${unresolved[1]}" for ${template}`);
  }

  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query ?? {})) {
    // `null` is a meaningful value in responses but never in a query string;
    // omitting both it and `undefined` lets callers spread optional filters.
    if (value === undefined || value === null) continue;

    // FastAPI reads repeated keys as a list (`?status=new&status=accepted`),
    // which is how the generated `string[]` params are meant to arrive.
    for (const item of Array.isArray(value) ? value : [value]) {
      if (item === undefined || item === null) continue;
      // URLSearchParams percent-encodes `+`, which matters for the `+00:00`
      // offset on the reporting window params — a raw `+` decodes to a space
      // server-side and fails datetime parsing.
      search.append(key, item instanceof Date ? item.toISOString() : String(item));
    }
  }

  const queryString = search.toString();
  return `${API_BASE_URL}${path}${queryString ? `?${queryString}` : ""}`;
}

// ---------------------------------------------------------------------------
// Request
// ---------------------------------------------------------------------------

async function request<T>(
  method: string,
  template: string,
  options: {
    path?: Record<string, unknown>;
    query?: Record<string, unknown>;
    body?: unknown;
    signal?: AbortSignal;
  } = {},
): Promise<T> {
  const url = buildUrl(template, options.path, options.query);

  const response = await fetch(url, {
    method,
    signal: options.signal,
    headers: options.body === undefined ? undefined : { "Content-Type": "application/json" },
    body: options.body === undefined ? undefined : JSON.stringify(options.body),
  });

  // 204 and empty bodies are valid; don't make callers guard against a parse.
  const raw = await response.text();
  const parsed = raw ? (JSON.parse(raw) as unknown) : null;

  if (!response.ok) {
    const detail =
      parsed && typeof parsed === "object" && "detail" in parsed
        ? (parsed as { detail: unknown }).detail
        : parsed;
    throw new ApiError(response.status, url, detail);
  }

  return parsed as T;
}

// ---------------------------------------------------------------------------
// Public surface
// ---------------------------------------------------------------------------

export const api = {
  get<P extends PathsWith<"get"> & keyof paths>(
    path: P,
    ...[options]: Args<P, "get">
  ): Promise<ResponseOf<P, "get">> {
    return request("GET", path as string, options as Parameters<typeof request>[2]);
  },

  post<P extends PathsWith<"post"> & keyof paths>(
    path: P,
    ...[options]: Args<P, "post">
  ): Promise<ResponseOf<P, "post">> {
    return request("POST", path as string, options as Parameters<typeof request>[2]);
  },
};
