/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Pull the 20 target accounts from the Rox customer hierarchy.
         */
        post: operations["sync_accounts_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Columns */
        get: operations["list_columns_research_columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_research_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description Filterable pipeline view — the backing query for the opportunity list.
         */
        get: operations["list_opportunities_opportunities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Counts for the pipeline header — how much is waiting, and how much has gone stale.
         *
         *     Kept out of the list response because it is a property of the queue rather
         *     than of the current page, and computed here rather than in the browser: it
         *     spans every pending row, not just the ones that fit in one page.
         */
        get: operations["get_stats_opportunities_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Opportunity */
        get: operations["get_opportunity_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description Accept or reject. Accepting kicks off prospecting in the background.
         */
        post: operations["decide_opportunities__opportunity_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospecting/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sequences */
        get: operations["list_sequences_prospecting_sequences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospecting/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sequence For Opportunity */
        get: operations["get_sequence_for_opportunity_prospecting_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospecting/opportunities/{opportunity_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Prospecting
         * @description Manually trigger prospecting — used to retry after a failure.
         */
        post: operations["rerun_prospecting_prospecting_opportunities__opportunity_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview
         * @description Everything the dashboard needs in one round trip.
         */
        get: operations["get_overview_reporting_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/funnel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Funnel */
        get: operations["get_funnel_reporting_funnel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/score-calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Score Calibration
         * @description Acceptance rate by score band — is the qualification score predictive?
         */
        get: operations["get_score_calibration_reporting_score_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/signal-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Signal Performance */
        get: operations["get_signal_performance_reporting_signal_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/decision-latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decision Latency */
        get: operations["get_decision_latency_reporting_decision_latency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/rejection-reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rejection Reasons */
        get: operations["get_rejection_reasons_reporting_rejection_reasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/account-coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Coverage */
        get: operations["get_account_coverage_reporting_account_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/prospecting-yield": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prospecting Yield */
        get: operations["get_prospecting_yield_reporting_prospecting_yield_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/job-telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Telemetry
         * @description Live Rox task-queue health (task types, states, cell-generation time).
         */
        get: operations["get_job_telemetry_reporting_job_telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reporting/run-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Health */
        get: operations["get_run_health_reporting_run_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/research/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Research
         * @description Run one research cycle now. Each opportunity notifies as it's created.
         */
        post: operations["trigger_research_admin_research_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_notifications__notification_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/notify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify Now
         * @description Re-send the notification for one opportunity.
         */
        post: operations["notify_now_opportunities__opportunity_id__notify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/notifications/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Digest
         * @description Email everything currently awaiting review as one digest.
         */
        post: operations["trigger_digest_admin_notifications_digest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rox/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rox Me
         * @description Connectivity check — confirms the token reaches Rox.
         */
        get: operations["rox_me_admin_rox_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCoverageOut */
        AccountCoverageOut: {
            /** Total Accounts */
            total_accounts: number;
            /** Accounts With Opportunities */
            accounts_with_opportunities: number;
            /** Coverage Rate */
            coverage_rate: number;
            /** Uncovered Accounts */
            uncovered_accounts: components["schemas"]["UncoveredAccountOut"][];
        };
        /** AccountOut */
        AccountOut: {
            /** Id */
            id: string;
            /** Rox Entity Id */
            rox_entity_id: string;
            /** Name */
            name: string;
            /** Domain */
            domain?: string | null;
            /** Industry */
            industry?: string | null;
            /** Parent Rox Entity Id */
            parent_rox_entity_id?: string | null;
            /**
             * Synced At
             * Format: date-time
             */
            synced_at: string;
        };
        /**
         * Channel
         * @enum {string}
         */
        Channel: "email";
        /** ContactOut */
        ContactOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Email */
            email?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** Persona */
            persona?: string | null;
            /** Match Reason */
            match_reason?: string | null;
            /** Score */
            score?: number | null;
        };
        /** DecisionIn */
        DecisionIn: {
            decision: components["schemas"]["DecisionType"];
            /** Decided By */
            decided_by?: string | null;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** DecisionLatencyOut */
        DecisionLatencyOut: {
            /** Count */
            count: number;
            /** Measured */
            measured: number;
            /** From Notification */
            from_notification: number;
            /** From Creation */
            from_creation: number;
            /** Median Hours */
            median_hours?: number | null;
            /** P90 Hours */
            p90_hours?: number | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Id */
            id: string;
            decision: components["schemas"]["DecisionType"];
            /** Decided By */
            decided_by?: string | null;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Notes */
            notes?: string | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Latency Seconds */
            latency_seconds?: number | null;
        };
        /**
         * DecisionType
         * @enum {string}
         */
        DecisionType: "accept" | "reject";
        /** DigestResultOut */
        DigestResultOut: {
            /** Sent */
            sent: boolean;
            /** Count */
            count: number;
            /** Recipient */
            recipient?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * EmailStatus
         * @enum {string}
         */
        EmailStatus: "draft" | "scheduled" | "sent" | "opened" | "replied";
        /** EnrollmentOut */
        EnrollmentOut: {
            /** Id */
            id: string;
            status: components["schemas"]["EnrollmentStatus"];
            /**
             * Enrolled At
             * Format: date-time
             */
            enrolled_at: string;
            contact: components["schemas"]["ContactOut"];
            /** Emails */
            emails?: components["schemas"]["OutreachEmailOut"][];
        };
        /**
         * EnrollmentStatus
         * @enum {string}
         */
        EnrollmentStatus: "pending" | "active" | "replied" | "bounced" | "completed";
        /** FunnelOut */
        FunnelOut: {
            /** Steps */
            steps: components["schemas"]["FunnelStepOut"][];
            /** Rejected */
            rejected: number;
        };
        /** FunnelStepOut */
        FunnelStepOut: {
            stage: components["schemas"]["Stage"];
            /** Count */
            count: number;
            /** Pct Of Total */
            pct_of_total: number;
            /** Pct Of Previous */
            pct_of_previous?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeadlineOut */
        HeadlineOut: {
            /** Total Opportunities */
            total_opportunities: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Pending Review */
            pending_review: number;
            /** Acceptance Rate */
            acceptance_rate: number;
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Scheduler Running */
            scheduler_running: boolean;
            /** Next Research Run */
            next_research_run?: string | null;
            /** Email Enabled */
            email_enabled: boolean;
            /** Rox Token Configured */
            rox_token_configured: boolean;
        };
        /** JobStateCountOut */
        JobStateCountOut: {
            /** State */
            state: string;
            /** Count */
            count: number;
        };
        /** JobTelemetryOut */
        JobTelemetryOut: {
            /** Lookback Hours */
            lookback_hours: number;
            /** Total Jobs */
            total_jobs: number;
            /** By Task Type */
            by_task_type: components["schemas"]["TaskTypeTelemetryOut"][];
            /** Avg Cell Generation Seconds */
            avg_cell_generation_seconds?: number | null;
        };
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: string;
            channel: components["schemas"]["Channel"];
            /** Recipient */
            recipient?: string | null;
            status: components["schemas"]["NotificationStatus"];
            /** Error */
            error?: string | null;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Sent At */
            sent_at?: string | null;
        };
        /**
         * NotificationStatus
         * @enum {string}
         */
        NotificationStatus: "pending" | "sent" | "failed";
        /** OpportunityDetailOut */
        OpportunityDetailOut: {
            /** Id */
            id: string;
            /** Account Id */
            account_id: string;
            /** Account Name */
            account_name?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            /** Qualification Score */
            qualification_score: number;
            /** Signal Type */
            signal_type: string;
            /** Signal Label */
            signal_label?: string | null;
            /** Needs Review */
            needs_review: boolean;
            status: components["schemas"]["OpportunityStatus"];
            stage: components["schemas"]["Stage"];
            /** Assigned To */
            assigned_to?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Notified At */
            notified_at?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Research */
            research?: components["schemas"]["ResearchArtifactOut"][];
            decision?: components["schemas"]["DecisionOut"] | null;
            /** Notifications */
            notifications?: components["schemas"]["NotificationOut"][];
            /**
             * Has Sequence
             * @default false
             */
            has_sequence: boolean;
        };
        /** OpportunityListOut */
        OpportunityListOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["OpportunityOut"][];
        };
        /** OpportunityOut */
        OpportunityOut: {
            /** Id */
            id: string;
            /** Account Id */
            account_id: string;
            /** Account Name */
            account_name?: string | null;
            /** Run Id */
            run_id?: string | null;
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            /** Qualification Score */
            qualification_score: number;
            /** Signal Type */
            signal_type: string;
            /** Signal Label */
            signal_label?: string | null;
            /** Needs Review */
            needs_review: boolean;
            status: components["schemas"]["OpportunityStatus"];
            stage: components["schemas"]["Stage"];
            /** Assigned To */
            assigned_to?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Notified At */
            notified_at?: string | null;
            /** Decided At */
            decided_at?: string | null;
        };
        /**
         * OpportunityStatus
         * @enum {string}
         */
        OpportunityStatus: "new" | "accepted" | "rejected";
        /** OutreachEmailOut */
        OutreachEmailOut: {
            /** Id */
            id: string;
            /** Step Number */
            step_number: number;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            status: components["schemas"]["EmailStatus"];
            /** Send At */
            send_at?: string | null;
            /** Sent At */
            sent_at?: string | null;
        };
        /** OverviewOut */
        OverviewOut: {
            headline: components["schemas"]["HeadlineOut"];
            funnel: components["schemas"]["FunnelOut"];
            score_calibration: components["schemas"]["ScoreCalibrationOut"];
            /** Signal Performance */
            signal_performance: components["schemas"]["SignalPerformanceOut"][];
            decision_latency: components["schemas"]["DecisionLatencyOut"];
            rejection_reasons: components["schemas"]["RejectionReasonsOut"];
            account_coverage: components["schemas"]["AccountCoverageOut"];
            prospecting_yield: components["schemas"]["ProspectingYieldOut"];
            run_health: components["schemas"]["RunHealthOut"];
        };
        /**
         * PipelineStatsOut
         * @description Queue health for the pipeline header.
         *
         *     Deliberately independent of the caller's filters: this answers "how is the
         *     review queue doing", which stays true regardless of what the user is
         *     currently looking at. Filtered counts are already on `OpportunityListOut`.
         */
        PipelineStatsOut: {
            /** Pending */
            pending: number;
            /** Aging */
            aging: number;
            /** Aging Threshold Hours */
            aging_threshold_hours: number;
        };
        /** ProspectingYieldOut */
        ProspectingYieldOut: {
            /** Accepted Opportunities */
            accepted_opportunities: number;
            /** Sequences Active */
            sequences_active: number;
            /** Activation Rate */
            activation_rate: number;
            /** Total Contacts */
            total_contacts: number;
            /** Total Emails Drafted */
            total_emails_drafted: number;
            /** Avg Contacts Per Accepted */
            avg_contacts_per_accepted: number;
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "good_fit" | "bad_timing" | "wrong_persona" | "already_engaged" | "low_signal" | "other";
        /** RecentRunOut */
        RecentRunOut: {
            /** Id */
            id: string;
            /** Trigger */
            trigger: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Accounts Scanned */
            accounts_scanned: number;
            /** Cells Fetched */
            cells_fetched: number;
            /** Opportunities Created */
            opportunities_created: number;
        };
        /** RejectionReasonOut */
        RejectionReasonOut: {
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Count */
            count: number;
            /** Pct */
            pct: number;
        };
        /** RejectionReasonPointOut */
        RejectionReasonPointOut: {
            /** Period */
            period: string;
            reason_code?: components["schemas"]["ReasonCode"] | null;
            /** Count */
            count: number;
        };
        /** RejectionReasonsOut */
        RejectionReasonsOut: {
            /** Total Rejections */
            total_rejections: number;
            /** Reasons */
            reasons: components["schemas"]["RejectionReasonOut"][];
            /** Group By */
            group_by?: string | null;
            /** Series */
            series?: components["schemas"]["RejectionReasonPointOut"][];
        };
        /** ResearchArtifactOut */
        ResearchArtifactOut: {
            /** Id */
            id: string;
            /** Column Key */
            column_key?: string | null;
            /** Column Name */
            column_name?: string | null;
            /** Cell Value */
            cell_value?: string | null;
            /** Signals */
            signals?: components["schemas"]["ResearchSignalOut"][];
            /** Narrative */
            narrative?: string | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** ResearchColumnOut */
        ResearchColumnOut: {
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Rox Column Id */
            rox_column_id?: string | null;
            /** Active */
            active: boolean;
        };
        /** ResearchRunOut */
        ResearchRunOut: {
            /** Id */
            id: string;
            /** Trigger */
            trigger: string;
            status: components["schemas"]["RunStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Accounts Scanned */
            accounts_scanned: number;
            /** Cells Fetched */
            cells_fetched: number;
            /** Cells Timed Out */
            cells_timed_out: number;
            /** Artifacts Created */
            artifacts_created: number;
            /** Opportunities Created */
            opportunities_created: number;
            /** Error */
            error?: string | null;
        };
        /**
         * ResearchSignalOut
         * @description One signal recovered from a research cell.
         */
        ResearchSignalOut: {
            /** Signal */
            signal?: string | null;
            /** Evidence */
            evidence?: string | null;
            /** Score */
            score?: number | null;
        };
        /**
         * RoxIdentityOut
         * @description Whoever the configured token authenticates as.
         *
         *     Both fields are optional: this backs a connectivity check, and a reachable
         *     Rox that happens to omit a field should still report as reachable rather
         *     than failing response validation.
         */
        RoxIdentityOut: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
        };
        /** RoxMeOut */
        RoxMeOut: {
            /** Message */
            message: string;
            detail?: components["schemas"]["RoxIdentityOut"] | null;
        };
        /** RunHealthOut */
        RunHealthOut: {
            /** Runs Considered */
            runs_considered: number;
            /** Success Rate */
            success_rate: number;
            /** Total Cells Fetched */
            total_cells_fetched: number;
            /** Recent Runs */
            recent_runs: components["schemas"]["RecentRunOut"][];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "running" | "succeeded" | "partial" | "failed";
        /** RunTriggerOut */
        RunTriggerOut: {
            run: components["schemas"]["ResearchRunOut"];
            /**
             * Notified
             * @default 0
             */
            notified: number;
        };
        /** ScoreBandOut */
        ScoreBandOut: {
            /** Band */
            band: string;
            /** Lo */
            lo: number;
            /** Hi */
            hi: number;
            /** Decided */
            decided: number;
            /** Accepted */
            accepted: number;
            /** Acceptance Rate */
            acceptance_rate: number;
        };
        /** ScoreCalibrationOut */
        ScoreCalibrationOut: {
            /** Total Decided */
            total_decided: number;
            /** Buckets */
            buckets?: number | null;
            /** Bands */
            bands: components["schemas"]["ScoreBandOut"][];
        };
        /** SequenceOut */
        SequenceOut: {
            /** Id */
            id: string;
            /** Opportunity Id */
            opportunity_id: string;
            /** Account Id */
            account_id: string;
            /** Account Name */
            account_name?: string | null;
            /** Name */
            name: string;
            status: components["schemas"]["SequenceStatus"];
            /** Error */
            error?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enrollments */
            enrollments?: components["schemas"]["EnrollmentOut"][];
        };
        /**
         * SequenceStatus
         * @enum {string}
         */
        SequenceStatus: "draft" | "active" | "completed" | "failed";
        /** SignalPerformanceOut */
        SignalPerformanceOut: {
            /** Signal Type */
            signal_type: string;
            /** Label */
            label: string;
            /** Created */
            created: number;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Acceptance Rate */
            acceptance_rate: number;
        };
        /**
         * Stage
         * @enum {string}
         */
        Stage: "researched" | "opportunity_created" | "notified" | "accepted" | "rejected" | "prospected" | "sequenced" | "outreach_sent";
        /** TaskTypeTelemetryOut */
        TaskTypeTelemetryOut: {
            /** Task Type */
            task_type: string;
            /** Total */
            total: number;
            /** States */
            states: components["schemas"]["JobStateCountOut"][];
        };
        /** UncoveredAccountOut */
        UncoveredAccountOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
        };
    };
    sync_accounts_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOut"][];
                };
            };
        };
    };
    list_columns_research_columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchColumnOut"][];
                };
            };
        };
    };
    list_runs_research_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_opportunities_opportunities_get: {
        parameters: {
            query?: {
                /** @description new | accepted | rejected */
                status?: string[] | null;
                stage?: string[] | null;
                signal_type?: string[] | null;
                account_id?: string | null;
                min_score?: number | null;
                max_score?: number | null;
                needs_review?: boolean | null;
                /** @description matches account name or title */
                search?: string | null;
                /** @description created_at | score | decided_at | account | stage | status | signal_type */
                sort?: string;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_opportunities_stats_get: {
        parameters: {
            query?: {
                /** @description age past which a pending opportunity is stale */
                aging_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_opportunities__opportunity_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sequences_prospecting_sequences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SequenceOut"][];
                };
            };
        };
    };
    get_sequence_for_opportunity_prospecting_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SequenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_prospecting_prospecting_opportunities__opportunity_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SequenceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_reporting_overview_get: {
        parameters: {
            query?: {
                /** @description equal-width score buckets; 10 for deciles */
                buckets?: number | null;
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_funnel_reporting_funnel_get: {
        parameters: {
            query?: {
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunnelOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_calibration_reporting_score_calibration_get: {
        parameters: {
            query?: {
                /** @description equal-width score buckets; 10 for deciles. Omit for the default named bands (0-59, 60-74, 75-89, 90-100). */
                buckets?: number | null;
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreCalibrationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_signal_performance_reporting_signal_performance_get: {
        parameters: {
            query?: {
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalPerformanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decision_latency_reporting_decision_latency_get: {
        parameters: {
            query?: {
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionLatencyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rejection_reasons_reporting_rejection_reasons_get: {
        parameters: {
            query?: {
                /** @description bucket the `series` field by day or week; omit for totals only */
                group_by?: string | null;
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectionReasonsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_coverage_reporting_account_coverage_get: {
        parameters: {
            query?: {
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountCoverageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prospecting_yield_reporting_prospecting_yield_get: {
        parameters: {
            query?: {
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectingYieldOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_telemetry_reporting_job_telemetry_get: {
        parameters: {
            query?: {
                /** @description Rox-side lookback */
                lookback_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobTelemetryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_health_reporting_run_health_get: {
        parameters: {
            query?: {
                /** @description inclusive lower bound (ISO 8601) */
                start?: string | null;
                /** @description exclusive upper bound (ISO 8601) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHealthOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_research_admin_research_run_post: {
        parameters: {
            query?: {
                notify?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTriggerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_notifications_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_notifications__notification_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notify_now_opportunities__opportunity_id__notify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_digest_admin_notifications_digest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestResultOut"];
                };
            };
        };
    };
    rox_me_admin_rox_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoxMeOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
}
